In [10]:
print("Hi this is me Md. Rasel Ali") # kon cell er pore kon cell run hoy eta likha thake pase.




Hi this is me Md. Rasel Ali


In [2]:
import sys
print(sys.executable)

/usr/local/bin/python3.11


In [3]:
import sys
!{sys.executable} -m pip install numpy

In [4]:
# Numpy is a like array but mostly like list.
# Mathematical operation numpy diye easily kora jai.
# Numpy is faster. its mostly used in ML and AI sector.

import numpy as np

In [3]:
menu = np.array(['cheese', 'bbq', 'vegetables', 'spicy'])
print(menu)

['cheese' 'bbq' 'vegetables' 'spicy']


In [ ]:
# price = [100,250,380,60]
# print(price)

[100, 250, 380, 60]


In [ ]:
# price ta numpy te array hisebe rekhe use korle
price_np = np.array([100,250,380,60])
discounted_price = price_np * 0.8 # emn mathematical operations kora jai
print(discounted_price) 

[ 80. 200. 304.  48.]


In [7]:
empty_tables = np.zeros((2,3)) # mane 2 ta row and 3ta column er 2D array create hobe jar sob value 0
print(empty_tables)

[[0. 0. 0.]
 [0. 0. 0.]]


In [9]:
full_tables = np.ones((2,3)) # uporer tar ulta kaj holo, matrix er sob datar value 1 hoye gelo.
print(full_tables)

[[1. 1. 1.]
 [1. 1. 1.]]


In [10]:
bbq_boxes = np.full((2,3), 'BBQ') # BBQ dara sob value fill korlam
print(bbq_boxes)

[['BBQ' 'BBQ' 'BBQ']
 ['BBQ' 'BBQ' 'BBQ']]


In [ ]:
bbq_boxes[0,1] = 'VEGETABLE' # 0 row and 1 column er value change koralm.
print(bbq_boxes)

[['BBQ' 'VEG' 'BBQ']
 ['BBQ' 'BBQ' 'BBQ']]


In [29]:
# Let random kono value generate korbo 2,3 matrix form e.
random_discount = np.random.rand(2,3) # rand--> 0--1 er moddhe value generate kore randomly
print(random_discount)

[[0.31636889 0.973555   0.04227668]
 [0.14884444 0.27480401 0.034712  ]]


In [61]:
# Randomly integer number generate korte
random_int = np.random.randint(1,8, (2,3)) # mane 1--8 er moddhe number generate hobe. and 2,3 holo 2D array size.
print(random_int)


[[7 6 2]
 [6 6 2]]


In [ ]:
# Identity matrix generation
identity_matrix = np.identity(3) # 3*3 identity matrix generate korbe.
print(identity_matrix)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [ ]:
# Interval ba kichu number por por matrix er value chaile 
delivery_times = np.arange(0,121,15) # mane 0 theke 15 interval por por ekta value pabo upto 120 porjonto
print(delivery_times)

[  0  15  30  45  60  75  90 105 120]


In [11]:
# Specific vag e vag kore interval 
specific_interval = np.linspace(0,60,8) # 0 theke start and 60 porjonto and 8 vage vag hobe.
print(specific_interval)

[ 0.          8.57142857 17.14285714 25.71428571 34.28571429 42.85714286
 51.42857143 60.        ]


In [31]:
# Creating 2D array/ list inside another list
orders = np.array(
    [
        ['BBQ','CHEESE', 'CHICKEN'],
        ['VEG', 'SPICY', 'BEEF']
    ]
)
print(orders)

[['BBQ' 'CHEESE' 'CHICKEN']
 ['VEG' 'SPICY' 'BEEF']]


In [19]:
print(orders[1,0])

VEG


In [30]:
print(orders[1: ]) # mane 1st row er sob column dekhabe. egula ke slicing bola hoy.

[['VEG' 'SPICY']]


In [29]:
print(orders[ :, 1]) # only 1number column dekhte.

['CHEESE' 'SPICY']


In [ ]:
print(orders[1, 0:2]) # 1 number row er 0 theke 1 column porjonto dekhabe. comma deya mane oi column er sob.

['VEG' 'SPICY']


In [ ]:
print(orders[: , 1:]) # sobgula column and 1st col theke sobgula col

[['CHEESE' 'CHICKEN']
 ['SPICY' 'BEEF']]
